### PR TITLE
Limit number of rows in workflow archiver

### PR DESCRIPTION
**Pull request by SaravShah**
Added ```       objs.first(5000).  ``` to limit workflow archiver

### CODE REVIEW

**Comment by jmartin-sul** [comment]
i *think* @drh-stanford has done stuff with workflow-archiver in the past?  seems like it'd be good to get review on this from someone more familiar with this machinery.

@LynnMcRae, is there a github issue somewhere (either in this repo or `workflow-archiver-job`) describing the problem this PR is addressing?  my understanding from standup this morning is that workflow-archiver is taking too long to run, and since a cron job kicks it off hourly, many workflow-archiver processes are running on top of one another, because none finish in a timely fashion due to the backlog of rows to be archived.

**Comment by jmartin-sul** [comment]
@drh-stanford: that was @LynnMcRae's first idea, but it caused test failures 😄    turns out the unit tests use sqlite, and `LIMIT` is an oracle-ism.  i did a bit of looking online, and couldn't find an easy/obvious query based way to do limits/paging that was also compliant with the general sql standard (and not specific to a given DB).

**Comment by drh-stanford** [comment]
Ok. Maybe add the `.first(5000)` to the fetch here? https://github.com/sul-dlss/workflow-archiver/blob/2f7ba05433a2f9f1497b4c0e447adb3e789d0ff5/lib/dor/workflow_archiver.rb#L177

**Comment by jmartin-sul** [comment]
oh, cool.  i like @drh-stanford's suggestion.  if that's a thing you can do, i'd vote for that approach (i'm almost totally unfamiliar with the `sequel` gem).

**Comment by SaravShah** [comment]
Travis didn't pass - going back to the original solution for now...

**Comment by jmartin-sul** [comment]
though this specific PR is a response to a production issue that came up this week, this was apparently a thought that's been floating around for a while:  see #11

**Comment by drh-stanford** [comment]
Yeah, I'm not familiar with Sequel enough to know for sure, but the documentation suggests that you can limit reads by using `first` -- see https://github.com/jeremyevans/sequel#retrieving-records. Note that in their documentation I don't see `fetch` discussed -- the preferred method seems to be `each`.

**Comment by SaravShah** [comment]
closed in favor of #14

**Pull request closed without merging**
